CREATE TABLE orders (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id VARCHAR(255)   NOT NULL,
    amount      DECIMAL(19, 2) NOT NULL,
    status      VARCHAR(50)    NOT NULL
);

CREATE TABLE payments (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT         NOT NULL,
    amount   DECIMAL(19, 2) NOT NULL,
    status   VARCHAR(50)    NOT NULL,
    CONSTRAINT fk_payments_order FOREIGN KEY (order_id) REFERENCES orders (id)
);
